name: Deploy to EKS

on:
  push:
    paths:
      - 'k8s/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::123456789012:role/github-oidc-role
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name nodejs-eks-cluster --region us-east-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f Kubernetes/deployment.yaml
        kubectl apply -f Kubernetes/service.yaml
        kubectl apply -f Kubernetes/ingress.yaml
